spring:
  application:
    name: "expenceAccounting"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/expenceApp"
    password: "password"
    username: "root"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: on